sudo: required
dist: trusty
install: git clone https://github.com/"${TRAVIS_REPO_SLUG%%/*}"/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build linux-template-builder
after_success:
 - ls -l ~/qubes-builder/qubes-src/linux-template-builder/rpm/noarch
language: generic
env:
 - DISTS_VM=jessie USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=jessie+standard USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=jessie+minimal+no-recommends USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=stretch USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=stretch+standard USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=stretch+minimal+no-recommends USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=jessie USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TEMPLATE_ROOT_WITH_PARTITIONS=1
 - DISTS_VM=jessie+standard USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TEMPLATE_ROOT_WITH_PARTITIONS=1
 - DISTS_VM=jessie+minimal+no-recommends USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TEMPLATE_ROOT_WITH_PARTITIONS=1
 - DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TEMPLATE_ROOT_WITH_PARTITIONS=1
 - DISTS_VM=stretch+standard USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TEMPLATE_ROOT_WITH_PARTITIONS=1
 - DISTS_VM=stretch+minimal+no-recommends USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TEMPLATE_ROOT_WITH_PARTITIONS=1

# don't build tags which are meant for code signing only
branches:
  except:
    - /.*_.*/
